repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        name: ruff (lint)
        args:
          - --fix
          - --show-fixes
        types: [python]
      - id: ruff-format
        name: ruff (format)
        types: [python]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black
        language_version: python3
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
        args: ["--fix=auto"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        name: markdownlint (docs style)
        files: ^docs/.*\.md$
        args:
          - "--disable"
          - "MD013"
          - "MD033"

  - repo: local
    hooks:
      - id: docs-no-bare-fences
        name: "docs: no bare code fences"
        entry: |
          bash -c 'grep -RIn --exclude-dir=site --exclude-dir=.git -E "^```[[:space:]]*$" docs && echo "ERROR: Bare code fence without language in docs/" 1>&2 && exit 1 || true'
        language: system
        files: ^docs/.*\.md$
      - id: docs-no-triple-dash
        name: "docs: forbid --- visual separators"
        entry: |
          bash -c 'grep -RIn --exclude-dir=site --exclude-dir=.git -E "^[[:space:]]*---[[:space:]]*$" docs && echo "ERROR: Use *** or <hr> instead of --- in docs/" 1>&2 && exit 1 || true'
        language: system
        files: ^docs/.*\.md$
      - id: docs-lychee-internal
        name: "docs: link check (internal only)"
        entry: |
          bash -c 'lychee --no-progress --accept 200,206 --exclude-all-private --exclude-mail --include-fragments --scheme file --fail docs || exit 0'
        language: system
        files: ^docs/.*\.md$
        additional_dependencies: []

# Speed: run only on changed files by default; full repo scan via:
#   pre-commit run --all-files
default_stages: [commit, push]
# Local convenience aliases (optional):
#   pre-commit install
#   pre-commit install --hook-type pre-push
#   pre-commit run --all-files
