repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        name: ruff (lint)
        args:
          - --fix
          - --show-fixes
        types: [python]
      - id: ruff-format
        name: ruff (format)
        types: [python]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: black
        language_version: python3
        types: [python]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: mixed-line-ending
        args: ["--fix=auto"]

# Speed: run only on changed files by default; full repo scan via:
#   pre-commit run --all-files
default_stages: [commit, push]

# Local convenience aliases (optional):
#   pre-commit install
#   pre-commit install --hook-type pre-push
#   pre-commit run --all-files
