site_name: Meridian Runtime
site_description: Minimal, reusable graph runtime for Python.
repo_url: https://github.com/GhostWeaselLabs/meridian-runtime
site_url: https://ghostweasellabs.github.io/meridian-runtime/
edit_uri: edit/main/

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - toc.follow
    - search.suggest
    - search.highlight
    - header.autohide
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - styles/overrides.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GhostWeaselLabs/meridian-runtime
      name: GitHub
  generator: false

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Quickstart: quickstart.md
  - Examples: examples.md
  - Concepts:
      - Overview: ABOUT.md
      - Patterns: patterns.md
      - Observability: observability.md
  - API Reference: api.md
  - Troubleshooting: troubleshooting.md
  - Contributing:
      - Guide: contributing/CONTRIBUTING.md
      - Support: ../SUPPORT.md
      - Plans & Roadmaps: plan/

markdown_extensions:
  # Core MkDocs/Material-friendly extensions
  - admonition
  - toc:
      permalink: true
  - attr_list
  - def_list
  - footnotes
  - meta

  # PyMdown extensions for richer content features
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  # - sitemap:
  #     url: https://ghostweasellabs.github.io/meridian-runtime/
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     fallback_to_build_date: true
  #     type: timeago
  # - redirects:
  #     redirect_maps:
  #       old/page.md: new/page.md
  # - minify:
  #     minify_html: true
  # - google-analytics:
  #     tracking_id: UA-XXXXXXXXX-X
  #     anonymize_ip: true
