name: CI

on:
  push:
    branches:
      - main
      - "feature/**"
      - "feat/**"
      - "bugfix/**"
      - "chore/**"
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Lint, Type, and Test (Python 3.11)
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install uv
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Resolve and sync dependencies
        shell: bash
        run: |
          # Create a lock if missing; subsequent runs use the lock.
          if [ ! -f uv.lock ]; then
            uv lock
          fi
          uv sync

      - name: Lint (ruff)
        shell: bash
        run: |
          uv run ruff check .

      - name: Format check (black)
        shell: bash
        run: |
          uv run black --check .

      - name: Type check (mypy)
        shell: bash
        run: |
          uv run mypy src

      - name: Run tests (pytest + coverage)
        shell: bash
        run: |
          uv run pytest

      - name: Generate coverage XML
        shell: bash
        if: always()
        run: |
          uv run pytest --cov=src --cov-report=xml:coverage.xml

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  # Optional job to verify packaging metadata/build (lightweight smoke)
  package:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distributions
        run: |
          python -m build

      - name: Upload dists
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/**
